spring.application.name=Proyecto Oracle
server.port=8080

#Cambiar datos de conexion dependiendo de la configuracion (Windows)
spring.application.name=PROY ADMIN
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCL
#[Fijarse en la conexio de Oracle SQL si utilizan XE o Service name]
#spring.datasource.username=PROY_ADMIN
#spring.datasource.password=PROY_ADMIN
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLCDB
spring.datasource.username=PROY_ADMIN
spring.datasource.password=PROY_ADMIN
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Comprueba el esquema de la base de datos y las entidades creadas en el proyecto
#Habilitar cuando hay grandes cambios en el proyecto o en el esquema de la base de datos 
spring.jpa.hibernate.ddl-auto=update

#Nivel de log para mejor visibilidad (Usado para confirmar conexion del proyecto con la base de datos)

#logging.level.com.oracle=INFO
#logging.level.org.springframework.jdbc=INFO
#ogging.level.org.hibernate=INFO
