spring.application.name=Proyecto Oracle
server.port=8080

#Cambiar datos de conexion dependiendo de la configuracion (Windows)
#spring.application.name=Proyecto Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE [Fijarse en la conexio de Oracle SQL si utilizan XE o Service name]
#spring.datasource.username=PROY_ADMIN
#spring.datasource.password=PROY_ADMIN
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.application.name=Proyecto Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLCDB
spring.datasource.username=PROY_ADMIN
spring.datasource.password=PROY_ADMIN
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración Oracle con Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update

# Nivel de log para mejor visibilidad
logging.level.com.oracle=INFO
logging.level.org.springframework.jdbc=INFO
logging.level.org.hibernate=INFO

