-- Script para la creación de usuario, tablespace y tablas del proyecto de estacionamiento
-- Ejecutar como usuario SYS con privilegios AS SYSDBA
-- Oracle SQL Developer

SET SERVEROUTPUT ON;

-- Desactivar la restricción de prefijo C## (permite crear usuarios sin prefijo)
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; 
-- Verificar y eliminar usuario existente
DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'PROY_ADMIN';
  IF user_exists > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER PROY_ADMIN CASCADE';
    DBMS_OUTPUT.PUT_LINE('Usuario PROY_ADMIN eliminado.');
  END IF;
END;
/

-- Verificar y eliminar tablespace existente
DECLARE
  ts_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO ts_exists FROM dba_tablespaces WHERE tablespace_name = 'PROYECTO';
  IF ts_exists > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLESPACE PROYECTO INCLUDING CONTENTS AND DATAFILES';
    DBMS_OUTPUT.PUT_LINE('Tablespace PROYECTO eliminado.');
  END IF;
END;
/

-- Creación del tablespace
-- Para sistemas Mac/Linux con Docker:
CREATE TABLESPACE PROYECTO
    DATAFILE '/opt/oracle/oradata/ORCLCDB/PROYECTO-ADMIN.DBF' 
    SIZE 500M 
    AUTOEXTEND ON 
    NEXT 10M 
    MAXSIZE 5000M;

-- Para sistemas Windows (comentar la sección anterior y descomentar esta sección):
/*
CREATE TABLESPACE PROYECTO
    DATAFILE 'C:\APP\[USUARIO]\PRODUCT\18.0.0\ORADATA\XE\PROYECTO-ADMIN.DBF' 
    SIZE 500M 
    AUTOEXTEND ON 
    NEXT 10M 
    MAXSIZE 5000M;
*/

-- Nota: En Windows, reemplazar [USUARIO] con el nombre de usuario correspondiente.
-- Rutas comunes en Windows según la versión de Oracle:
-- Oracle 18c XE: C:\APP\[USUARIO]\PRODUCT\18.0.0\ORADATA\XE\
-- Oracle 19c:    C:\APP\[USUARIO]\PRODUCT\19.0.0\ORADATA\[SID]\
-- Oracle 21c:    C:\APP\[USUARIO]\PRODUCT\21.0.0\ORADATA\[SID]\

-- Creación de usuario (sin restricción de prefijo C## gracias a _ORACLE_SCRIPT=TRUE)
CREATE USER PROY_ADMIN IDENTIFIED BY PROY_ADMIN;

-- Asignación de permisos
GRANT CONNECT, RESOURCE TO PROY_ADMIN;
GRANT DBA TO PROY_ADMIN;
GRANT CREATE SESSION TO PROY_ADMIN;
GRANT UNLIMITED TABLESPACE TO PROY_ADMIN;

-- Asignación del tablespace
ALTER USER PROY_ADMIN DEFAULT TABLESPACE PROYECTO;
ALTER USER PROY_ADMIN TEMPORARY TABLESPACE TEMP;

-- Creación de tablas
-- Se conecta como PROY_ADMIN para crear las tablas
CONNECT PROY_ADMIN/PROY_ADMIN

CREATE TABLE ESTACIONAMIENTOS (
    ID_ESTACIONAMIENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    CAPACIDAD_TOTAL NUMBER(6) NOT NULL,
    HORARIO_APERTURA TIMESTAMP,
    HORARIO_CIERRE TIMESTAMP
);

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL
);

CREATE TABLE NIVELES (
    ID_NIVEL NUMBER PRIMARY KEY,
    ID_ESTACIONAMIENTO NUMBER,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    CAPACIDAD_NIVEL NUMBER(4) NOT NULL,
    CONSTRAINT FK_ESTACIONAMIENTOS FOREIGN KEY (ID_ESTACIONAMIENTO) 
    REFERENCES ESTACIONAMIENTOS(ID_ESTACIONAMIENTO)
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    NUMERO_PLACA VARCHAR2(12) NOT NULL,
    TIPO_VEHICULO VARCHAR2(20) NOT NULL,
    TIPO_ENERGIA VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_CLIENTES FOREIGN KEY (ID_CLIENTE) 
    REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE ESPACIOS (
    ID_ESPACIO NUMBER PRIMARY KEY,
    ID_NIVEL NUMBER,
    NUMERO_ESPACIO NUMBER(3) NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    UBICACION VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_NIVELES FOREIGN KEY (ID_NIVEL) 
    REFERENCES NIVELES(ID_NIVEL)
);

CREATE TABLE TICKETS (
    ID_TICKETS NUMBER PRIMARY KEY,
    ID_VEHICULO NUMBER,
    ID_ESPACIO NUMBER,
    FECHA_HORA_ENTRADA TIMESTAMP,
    FECHA_HORA_SALIDA TIMESTAMP,
    ESTADO VARCHAR2(15) NOT NULL,
    CONSTRAINT FK_VEHICULOS FOREIGN KEY (ID_VEHICULO) 
    REFERENCES VEHICULOS(ID_VEHICULO),
    CONSTRAINT FK_ESPACIOS FOREIGN KEY (ID_ESPACIO) 
    REFERENCES ESPACIOS(ID_ESPACIO)
);

CREATE TABLE TARIFAS (
    ID_TARIFA NUMBER PRIMARY KEY,
    TIPO_TARIFA VARCHAR2(20) NOT NULL,
    PRECIO NUMBER
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CARGO VARCHAR2(50) NOT NULL
);

CREATE TABLE PAGOS (
    ID_PAGO NUMBER PRIMARY KEY,
    ID_TICKETS NUMBER,
    ID_TARIFA NUMBER,
    ID_EMPLEADO NUMBER,
    FECHA_PAGO DATE,
    MONTO_TOTAL NUMBER,
    CONSTRAINT FK_TICKETS FOREIGN KEY (ID_TICKETS) 
    REFERENCES TICKETS(ID_TICKETS),
    CONSTRAINT FK_TARIFAS FOREIGN KEY (ID_TARIFA) 
    REFERENCES TARIFAS(ID_TARIFA),
    CONSTRAINT FK_EMPLEADOS FOREIGN KEY (ID_EMPLEADO) 
    REFERENCES EMPLEADOS(ID_EMPLEADO)
);

-- Creación de secuencias para los IDs
CREATE SEQUENCE SEQ_ESTACIONAMIENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NIVEL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VEHICULO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESPACIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TICKET START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TARIFA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLEADO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAGO START WITH 1 INCREMENT BY 1;

COMMIT;

-- Mensaje final
PROMPT ======================================================
PROMPT Instalación completada con éxito.
PROMPT Usuario: PROY_ADMIN
PROMPT Contraseña: PROY_ADMIN
PROMPT Tablespace: PROYECTO
PROMPT Todas las tablas han sido creadas.
PROMPT ======================================================